x =(0:0.1:10);
triy=trimf(x,[2 4 7]);
trapy=trapmf(x, [1 3 4 7]);
gaussy = gaussmf(x, [1 4]);
gauss2y = gauss2mf(x', [5 6 8 3]);
gbelly = gbellmf(x, [2 7 3]);
sigy = sigmf(x, [-1 3]);
dsigy = dsigmf(x, [3 4 5 6] );
psigy = psigmf(x, [1 3 4 6]);
zy= zmf(x, [2 5]);
piy = pimf (x, [1 4 6 8]);
sy = smf (x, [5 9]);
triy_1= trimf(x, [1 4 6]);
gaussy_1 = gaussmf(x, [2 3]);
triy_gaussy_min= min(triy_1, gaussy_1);
triy_gaussy_max= max(triy_1, gaussy_1);
triy_gaussy_prod = prod([triy_1; gaussy_1]);
triy_gaussy_probor = probor([triy_1; gaussy_1]);
gaussy_2 = gaussmf(x, [2 4]);
gauusy_negative= 1-gaussy_2;

figure;
subplot (1, 2, 1);
plot(x, triy);
title('трикутна ФП');
legend('trimf(x,[2 4 7])');
subplot (1, 2, 2);
plot(x, trapy);
title('трапецієподібна ФП');
legend('trapmf(x, [1 3 4 7])');
figure;
subplot (1, 3, 1);
plot(x, gaussy);
title('простa ФП Гаусса');
legend('gaussmf(x, [3 4])');
subplot (1, 3, 2);
plot(x', gauss2y);
title('двостороння ФП Гаусса');
legend('gauss2mf(x'', [5 6 8 3])');
subplot (1, 3, 3);
plot(x, gbelly);
title('ФП "узагальнений дзвін"');
legend('gbellmf(x, [2 7 3])');
figure;
subplot (1, 2, 1);
plot(x, [sigy; psigy; dsigy]);
title('сігмоіднi ФП');
legend('основна одностороння ФП' ,'додаткова двостороння ФП','додаткова несиметрична ФП');
subplot (1, 2, 2);
plot(x, [zy; piy; sy]);
title('поліноміальнi ФП');
legend('Z-ФП', 'PI-ФП', 'S-ФП');
figure;
subplot (2, 2, 1);
plot(x, [triy_1; gaussy_1], ':');
hold on;
plot(x, triy_gaussy_min, 'r');
hold off;
title('Перетин нечiтких множин (minmax)');
legend('trimf(x, [1 4 6])','gaussmf(x, [5 4])','min(triy_1, gaussy_1)');
subplot (2, 2, 2);
plot(x, [triy_1; gaussy_1], ':');
hold on;
plot(x, triy_gaussy_max, 'r');
hold off;
title('Oб''єднання нечiтких множин (minmax)');
legend('trimf(x, [1 4 6])','gaussmf(x, [5 4])','max(triy_1, gaussy_1)');
subplot (2, 2, 3);
plot(x, [triy_1; gaussy_1], ':');
hold on;
plot(x, triy_gaussy_prod, 'r');
hold off;
title('Перетин нечiтких множин (ймовірнісна інтерпретація)');
legend('trimf(x, [1 4 6])','gaussmf(x, [5 4])','prod([triy_1, gaussy_1)]');
subplot (2, 2, 4);
plot(x, [triy_1; gaussy_1], ':');
hold on;
plot(x, triy_gaussy_probor, 'r');
hold off;
title('Oб''єднання нечiтких множин (ймовірнісна інтерпретація)');
legend('trimf(x, [1 4 6])','gaussmf(x, [5 4])','probor([triy_1, gaussy_1])');
figure;
plot(x, gaussy_2, ':');
hold on;
plot(x, gauusy_negative);
hold off;
title('Доповнення нечіткої множини');
legend('y=gaussmf(x, [7 9])','1-y');
