options = optimoptions('ga', 'PlotFcn', {@gaplotbestf @gaplotbestindiv ...
@gaplotdistance},'Display', 'iter', 'MaxGenerations', 50, ...
'PopulationSize', 10);
rng default
y_in = 1;
y_interval = [0 5];
[x,y] = ga(@func1, y_in, [], [], [], [], y_interval(1), y_interval(2), ...
[], [], options);
fprintf('Min y = %f in %f\n', y, x);
figure
x_arg = 0:0.01:5;
hold on
plot(x_arg,func1(x_arg));
plot(x,y,'*', ...
'LineWidth',2,...
'MarkerSize',10,...
'MarkerEdgeColor','r')
hold off